### PR TITLE
Read with GeoArrow metadata for GDAL >= 3.8

### PR DESCRIPTION
**Pull request by kylebarron**
Resolves half of https://github.com/geopandas/pyogrio/issues/345. @jorisvandenbossche mentioned in https://github.com/geopandas/pyogrio/issues/345#issuecomment-1909638656 that he'd suggest making the change to geoarrow metadata. I'd also propose that we make this the default.

A test is added to verify that the metadata on the geometry field is set. The name should be `geoarrow.wkb` and the extension metadata should include a CRS field with PROJJSON, which I assert is EPSG:4326 for this test dataset.

@brendan-ward would you still prefer having a flag for the user to set this? Ref https://github.com/geopandas/pyogrio/issues/345#issuecomment-1908878875

### CODE REVIEW

**Comment by kylebarron** [comment]
This will be exciting to get working with [lonboard](https://github.com/developmentseed/lonboard), a visualization library I'm working on. I added [support for parsing from `geoarrow.wkb` input](https://github.com/developmentseed/lonboard/pull/372) and with the CRS information it'll do [multithreaded reprojection to WGS84](https://github.com/developmentseed/lonboard/pull/337), parallelizing over each Arrow chunk (conveniently GDAL will handle the chunking into row groups). So it should be really fast to plot (though today it still goes through shapely for the WKB -> GeoArrow parsing, which is a relative bottleneck, though still certainly fast enough)

**Review by jorisvandenbossche — APPROVED** [review]
Thanks! 
I am personally fine with just defaulting to geoarrow without providing an explicit keyword to control this (in the end it's just for the metadata, not the actual data you get)

**Review by brendan-ward — APPROVED** [review]
Thanks!

Seems reasonable to go with geoarrow as the default and no need for a keyword, especially since it makes downstream handling easier.

**Comment by brendan-ward** [comment]
Could you please add an entry to the changelog?

**Pull request merged**
