### PR TITLE
ENH: Add test of Arrow roundtrip of boolean values, raise exception on GDAL <3.8.3 for bool values via Arrow API

### PR DESCRIPTION
**Pull request by brendan-ward**
Test to reproduce #334 incorrect handling of boolean values using Arrow I/O (mostly to see if this also fails on GDAL >= 3.8.1).

As the root cause has been solved and released in GDAL, this PR now resolves https://github.com/geopandas/pyogrio/issues/334

### CODE REVIEW

**Comment by theroggy** [comment]
[GDAL 3.8.3](https://github.com/OSGeo/gdal/blob/v3.8.3/NEWS.md#vector-drivers) fixes this and has just been released...

**Comment by brendan-ward** [comment]
Because misreading boolean values is a **bad** error, this adds an exception to `read_arrow` if boolean values are detected in the pyarrow table read from GDAL.  I didn't add an exception to `open_arrow` because we don't know the contents of the stream it returns.  I'm assuming that given the severity of this bug, it is better to raise an exception and instruct users to avoid the arrow API for GDAL < 3.8.3 than to do something less intrusive like raise a warning that might be ignored by the user.

I used an `xfail` for the failing test case so that we can detect if this fix gets backported to other GDAL versions (e.g., if there is a 3.7.4 that includes it)

**Comment by theroggy** [comment]
> Because misreading boolean values is a **bad** error, this adds an exception to `read_arrow` if boolean values are detected in the pyarrow table read from GDAL. I didn't add an exception to `open_arrow` because we don't know the contents of the stream it returns. I'm assuming that given the severity of this bug, it is better to raise an exception and instruct users to avoid the arrow API for GDAL < 3.8.3 than to do something less intrusive like raise a warning that might be ignored by the user.

Good idea!

> I used an `xfail` for the failing test case so that we can detect if this fix gets backported to other GDAL versions (e.g., if there is a 3.7.4 that includes it)

I'm not sure if the xfail is that interesting as the test testing for the exception for GDAL < 3.8 will fail anyway. It feels like it's a pity that it is not possible to specify a "match" in the xfail decorator. If that would be possible I think the "exception" test could be replaced by that using only the xfail, or am I missing something?

**Review by theroggy — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
According to the GDAL PR fixing this, this only affects reading GPKG/FlatGeoBuf files. Would we have a way to check for that? (we don't know the driver because that gets inferred while reading, except if we explicitly get that info (``read_info`` returns it?). But maybe we could then only do that when we detect there is a boolean column)

**Comment by brendan-ward** [comment]
Indeed; I had assumed it applied to all the bool drivers because it was in `OGRArrowArrayHelper::SetBoolOn()` (even though it did specifically mention only those drivers).

It looks like boolean values roundtripped properly for SQLite / GeoJSON / GML (not able to easily test postgres) - so our exception would be raised when the functionality is just fine.  Will add a fix for this.

**Comment by jorisvandenbossche** [comment]
Maybe it is because that utility function is only used by drivers that have a custom implementation of GetArrowStream that sidesteps the internal GDAL data model (which are only GPKG and FlatGeoBuf, AFAIK, apart from Parquet/Arrow, but those already are already in arrow format after reading, of course). Other drivers fall back to a default implementation based on the standard APIs to read data (like we also use)

**Pull request merged**
